#---------------------------------------------------------------------------------------------------------
# INFORMACION DE LA APLICACION
#---------------------------------------------------------------------------------------------------------
spring.application.name=store
server.port = 9092

#---------------------------------------------------------------------------------------------------------
# CONFIGURACION DE API-DOCS
#---------------------------------------------------------------------------------------------------------
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
#http://localhost:9092/swagger-ui/index.html

#---------------------------------------------------------------------------------------------------------
# CONFIGURACION DE DATASOURCE
#---------------------------------------------------------------------------------------------------------
spring.datasource.url = jdbc:postgresql://localhost:5432/tienda92
spring.datasource.username = postgres
spring.datasource.password = 123456

#---------------------------------------------------------------------------------------------------------
# CONFIGURACION DE JPA
#---------------------------------------------------------------------------------------------------------
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = update
##spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true

#---------------------------------------------------------------------------------------------------------
# CONFIGURACION DE API FeignClient
#---------------------------------------------------------------------------------------------------------
client.api-fake = https://dog.ceo/api/breeds/image

#---------------------------------------------------------------------------------------------------------
# CONFIGURACION DE LOGS
#---------------------------------------------------------------------------------------------------------
spring.main.banner-mode=console
#logging.file.name=
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} | [%thread] | %-5level | %logger{36} - %msg%n
#logging.logback.rollingpolicy.max-file-size=2MB

#----------------------------------------------------------------------------------------------------------
# CONFIGURACION DE CORS
#----------------------------------------------------------------------------------------------------------
# En produccion se recomienda deshabilitar CORS, ya que se debe controlar desde el gateway o desde el servidor web.
cors.enabled=true
cors.allowed-origins=http://localhost:4200
cors.allowed-methods=*
cors.allowed-headers=*
# Indica si se permiten las credenciales, por default se calcula dependiendo de cors.allowed-origins
#cors.allow-credentials=true
