spring.application.name=store

spring.datasource.url = jdbc:postgresql://localhost:5432/tienda92

spring.jpa.hibernate.ddl-auto = update
spring.datasource.username = postgres
spring.datasource.password = 123456
server.port = 9092

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true